apiVersion: batch/v1
kind: Job
metadata:
  name: test-1234-768e9c
  namespace: default
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  suspend: false
  template:
    spec:
      containers:
      - args:
        - /payload/request.json
        command:
        - /backup-tool
        image: k3d-registry.localhost:12345/psmdb-backup-tool:latest
        imagePullPolicy: Always
        name: importer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30