// Copyright (C) 2026 The OpenEverest Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generate

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Options configures the generate command.
type Options struct {
	// DefinitionDir is the path to the definition directory (default: "definition").
	DefinitionDir string

	// ChartDir is the path to the Helm chart directory.
	// If empty, auto-detected as charts/<provider-name> from definition/provider.yaml.
	ChartDir string

	// TypesPackages are Go package patterns for type definition loading.
	// Default: ["./definition/..."]
	TypesPackages []string
}

// Run assembles definition/ files, resolves Go type schemas, and writes
// the Provider CR spec to charts/<name>/generated/provider-spec.yaml.
//
// This follows the same pattern as RBAC generation:
//
//	controller-gen → config/rbac/role.yaml → helm-sync-rbac → charts/.../generated/rbac-rules.yaml
//	definition/    → provider-sdk generate →                   charts/.../generated/provider-spec.yaml
func Run(opts Options) error {
	if opts.DefinitionDir == "" {
		opts.DefinitionDir = "definition"
	}
	if len(opts.TypesPackages) == 0 {
		opts.TypesPackages = []string{"./definition/..."}
	}

	// 1. Assemble definition/ files into internal config.
	cfg, err := Assemble(opts.DefinitionDir)
	if err != nil {
		return fmt.Errorf("assembling definition files: %w", err)
	}

	// Auto-detect chart dir if not specified.
	if opts.ChartDir == "" {
		detected, err := detectChartDir()
		if err != nil {
			return fmt.Errorf("auto-detecting chart directory: %w; specify --chart-dir explicitly", err)
		}
		opts.ChartDir = detected
	}

	// 2. Resolve Go type schemas if any type references found.
	typeNames := make([]string, 0, len(cfg.TypeRefs))
	for name := range cfg.TypeRefs {
		typeNames = append(typeNames, name)
	}

	var schemas map[string]any
	if len(typeNames) > 0 {
		schemas, err = ResolveSchemas(opts.TypesPackages, typeNames)
		if err != nil {
			return fmt.Errorf("resolving type schemas: %w", err)
		}
	}

	// 3. Build the Provider CR spec map with schemas injected.
	specMap := buildSpecMap(cfg, schemas)

	// 4. Write to chart generated directory.
	outputDir := filepath.Join(opts.ChartDir, "generated")
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	outputFile := filepath.Join(outputDir, "provider-spec.yaml")

	var buf bytes.Buffer
	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)
	if err := encoder.Encode(map[string]any{"spec": specMap}); err != nil {
		return fmt.Errorf("marshaling spec: %w", err)
	}
	encoder.Close()

	header := "# This file is generated by `provider-sdk generate` from definition/ files.\n" +
		"# Do not edit manually. Run `make generate` to update.\n"

	if err := os.WriteFile(outputFile, []byte(header+buf.String()), 0o644); err != nil {
		return fmt.Errorf("writing output: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Generated: %s\n", outputFile)
	return nil
}

// detectChartDir finds the Helm chart directory by scanning charts/ for
// subdirectories containing a Chart.yaml file.
func detectChartDir() (string, error) {
	entries, err := os.ReadDir("charts")
	if err != nil {
		return "", fmt.Errorf("reading charts/ directory: %w", err)
	}

	var candidates []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		chartFile := filepath.Join("charts", entry.Name(), "Chart.yaml")
		if _, err := os.Stat(chartFile); err == nil {
			candidates = append(candidates, filepath.Join("charts", entry.Name()))
		}
	}

	switch len(candidates) {
	case 0:
		return "", fmt.Errorf("no Helm charts found in charts/")
	case 1:
		return candidates[0], nil
	default:
		return "", fmt.Errorf("multiple Helm charts found in charts/: %v", candidates)
	}
}

// buildSpecMap constructs the Provider CR spec as a map, with type references
// replaced by their resolved OpenAPI schemas.
func buildSpecMap(cfg *AssembledConfig, schemas map[string]any) map[string]any {
	spec := make(map[string]any)

	if cfg.ComponentTypes != nil {
		spec["componentTypes"] = cfg.ComponentTypes
	}

	// Components — resolve customSpecSchema references.
	if cfg.Components != nil {
		comps := make(map[string]any)
		for name, compRaw := range cfg.Components {
			if comp, ok := compRaw.(map[string]any); ok {
				resolved := make(map[string]any)
				for k, v := range comp {
					if k == "customSpecSchema" {
						if typeName, ok := v.(string); ok && schemas != nil {
							if schema, ok := schemas[typeName]; ok {
								resolved[k] = schema
							}
						}
					} else {
						resolved[k] = v
					}
				}
				comps[name] = resolved
			} else {
				comps[name] = compRaw
			}
		}
		spec["components"] = comps
	}

	// Topologies — resolve configSchema references.
	if cfg.Topologies != nil {
		topos := make(map[string]any)
		for name, topoRaw := range cfg.Topologies {
			if topo, ok := topoRaw.(map[string]any); ok {
				resolved := make(map[string]any)
				for k, v := range topo {
					if k == "configSchema" {
						if typeName, ok := v.(string); ok && schemas != nil {
							if schema, ok := schemas[typeName]; ok {
								resolved[k] = schema
							}
						}
					} else {
						resolved[k] = v
					}
				}
				topos[name] = resolved
			} else {
				topos[name] = topoRaw
			}
		}
		spec["topologies"] = topos
	}

	// Global config schema.
	if cfg.GlobalConfigSchema != "" && schemas != nil {
		if schema, ok := schemas[cfg.GlobalConfigSchema]; ok {
			spec["globalConfigSchema"] = schema
		}
	}

	if cfg.UISchema != nil {
		spec["uiSchema"] = cfg.UISchema
	}

	return spec
}
